added dark mode in about us page and services page
07sumit1002/CabRental pull request #242
Opened 2024-10-06 11:02 UTC by Deepika14145

# 🚀 Pull Request

## Description

Please include a summary of the changes and the related issue. Provide relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of Change

- [+] New feature (non-breaking change which adds functionality)
- added dark mode in about us page and services page

## Checklist:

- [+] My code follows the style guidelines of this project
- [+] I have performed a self-review of my own code
- [+] I have commented my code, particularly in hard-to-understand areas
- [+] I have made corresponding changes to the documentation
- [+] My changes generate no new warnings
- [+] I have added tests that prove my fix is effective or that my feature works
- [+] New and existing unit tests pass locally with my changes
- [+] Any dependent changes have been merged and published in downstream modules

## Screenshot of final output/video
about us page -
![Screenshot 2024-10-06 163103](https://github.com/user-attachments/assets/a26ed963-ad90-4c7d-b5e2-585721c9e002)
services page -
![Screenshot 2024-10-06 163218](https://github.com/user-attachments/assets/e4251bec-4c76-495c-8244-3b3037bd1c49)

2024-10-06 15:36 UTC, Deepika14145 commented
Please review @sanjay-kv

2024-10-06 19:09 UTC, akbatra567 commented on about.html
> +            src="https://imgs.search.brave.com/q0e8cW8B-XzUbrgZx4qP0ObqkV3g5cPE82Dptj32vVY/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9pbWcu/ZnJlZXBpay5jb20v/ZnJlZS1waG90by9w/aG90by1jb250ZW50/LzIwMTkvMDMvbXNo/aXN
Could you download the image and import from local url ?
This image is not showing up. 

<img width="1141" alt="Screenshot 2024-10-07 at 00 39 26" src="https://github.com/user-attachments/assets/8525d5ae-af21-4da1-ba92-256971039831">

2024-10-06 19:14 UTC, akbatra567 commented on about.html
> +          <li>Integrity</li>
Could you share your thoughts behind changing the content ? 

Also as the description is removed 

After:

2024-10-06 19:19 UTC, akbatra567 commented on about.html
> +          <li>Customer Satisfaction</li>
Could you share the thoughts behind changing the content ? 

Also after changing content there's a lot of white space that it feels empty. 

Suggestions: 
1. Experiment with text alignment.
2. Experiment with the box sizing if we even need that big values and principles boxes. 

<img width="1232" alt="Screenshot 2024-10-07 at 00 43 54" src="https://github.com/user-attachments/assets/f2a03a0d-7571-486c-9f8a-da022d025556">

2024-10-06 19:22 UTC, akbatra567 requested changes
I see some common styles related to dark mode theme which is added to both `about.html` and `serv.html` and would be similar for other pages. Could you create an external css file and transfer the common css there and import that and verify if it works the same.

2024-10-07 01:13 UTC, Deepika14145 commented
I will check all above mentioned issues and will work on ìt.

2024-10-07 16:55 UTC, Deepika14145 commented
Sorry for late actually my exams are going on I will update it soon @akbatra567

2024-10-13 06:49 UTC, Deepika14145 commented
Can you please review the changes that I have made @akbatra567 ? I have committed some changes.

2024-10-14 19:22 UTC, akbatra567 commented
> Hello, @akbatra567 Please review the changes I have made in PR.

Requested changes are missing: 

> I see some common styles related to dark mode theme which is added to both about.html and serv.html and would be similar for other pages. Could you create an external css file and transfer the common css there and import that and verify if it works the same.


Let me explain this a bit on what you need to do: 
1. See what all common styles you are using for the 2 html pages.
2. create a common css file name could be anything you feel adds more value, suggestions: `dark.css` - in case you only copy dark theme styles, else could be `main.css` / `common.css`
3. Import this newly created css file inside the html files replacing the duplicated code from the files. using `<link rel="stylesheet" href='<add file path here>'>`
4. Verify the styles if it working as expected. 
5. Tag me when you complete these.

2024-10-20 09:14 UTC, Deepika14145 commented
ok @akbatra567 i will update it soon

2024-10-27 06:24 UTC, merged

2024-10-27 06:59 UTC, Deepika14145 commented
If this PR is merged then why its not showing "Accepted" on hacktoberbest website @07sumit1002

2024-10-27 07:02 UTC, Deepika14145 commented
please add hacktoberfest-accepted labels to this PR @07sumit1002 and labels