Contact form
07sumit1002/CabRental pull request #291
Opened 2024-10-07 17:36 UTC by swathivemula7

# 🚀 Pull Request

Fixes #201

I have enhanced the UI of the contact form and aligned it well with the website..

Screenshot of the contact form created:
![Captureddnfde](https://github.com/user-attachments/assets/f67bac1c-5d0e-44e7-886c-aa3e0deab51b)

Kindly review at the earliest..

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-10-15 15:49 UTC, swathivemula7 commented
@07sumit1002 Kindly review the PR at the earliest

2024-10-19 18:59 UTC, swathivemula7 commented
@07sumit1002 It's been almost 2 weeks since the PR has been raised...so please review it at the earliest..

2024-10-22 17:28 UTC, swathivemula7 commented
@akbatra567 @07sumit1002 Kindly review the PR at the earliest..

2024-10-23 07:12 UTC, akbatra567 requested changes
Could you align the contact form within the contact me section ?

Also see the size of form, contact me and the above FAQ sections very different, could you change it to be the same size and make sure it is responsive.  

<img width="598" alt="image" src="https://github.com/user-attachments/assets/10bc4616-19e1-4693-aa94-67041c60a341">

2024-10-23 07:13 UTC, akbatra567 commented on index.html
> +                <form name="submit-to-google-sheet" class="contact-form">
Could you make the form method to be post instead of get ? right now when we click submit it shows all the data in the address bar.

2024-10-23 07:33 UTC, swathivemula7 commented
@akbatra567 ok..I will make the required changes

2024-10-23 10:14 UTC, swathivemula7 commented
I have the made the requested changes..
1. Aligned contact form inside contact-me section.
2. Aligned faq and contact section to the same size..
3. Also I have made it mobile responsive..
4. And I have changes the form method to "post"

![Capturenjn](https://github.com/user-attachments/assets/d7feae02-c554-43c5-ac61-d5b3c4177263)

@akbatra567  Please review and consider giving a deserving label..

2024-10-24 05:58 UTC, merged